version: '3'
services:
  servidor:
    build:
      context: ./BratislavaApi
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: bratislava
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: mateus@venancio.com
      PGADMIN_DEFAULT_PASSWORD: mateus
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - '5050:5050'
    depends_on:
      - db